root -l -q -b makeRatio.C' ("njet/njet_fit__expected_ggH_ggH.dat", "njet/njet_binbybin__fit__expected_ggH_ggH.dat", "njet/njetggHpred.dat", "ggH_ggH")'
root -l -q -b makeRatio.C' ("njet/njet_fit__expected_ggH_MG5.dat", "njet/njet_binbybin__fit__expected_ggH_MG5.dat", "njet/njetmg.dat", "ggH_MG5")'
root -l -q -b makeRatio.C' ("njet/njet_fit__expected_ggH_VBF.dat", "njet/njet_binbybin__fit__expected_ggH_VBF.dat", "njet/njetVBFpred.dat", "ggH_VBF")'
root -l -q -b makeRatio.C' ("njet/njet_fit__expected_ggH_ZH.dat", "njet/njet_binbybin__fit__expected_ggH_ZH.dat", "njet/njetZHpred.dat", "ggH_ZH")'
root -l -q -b makeRatio.C' ("njet/njet_fit__expected_ggH_WH.dat", "njet/njet_binbybin__fit__expected_ggH_WH.dat", "njet/njetWHpred.dat", "ggH_WH")'
